name: Build Docker image dev
on:
  push:
    # Run pipeline for commits on branch main
    branches:
      - "main"
      - "Snekha/test" #edited
      - "!testing/**"
      - "!feature/**"
      - "!hotfix/**"

jobs:
  build-dev:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: srivmanish
          password: Hcl@20252026
      - name: Build and push dev
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: srivmanish/telegram-to-rss1:dev
          platforms: linux/amd64,linux/arm64
      #added below
      - name: Run container
        run: |
          docker run -d --name telegram_test \
            -e TG_API_ID=123456 \
            -e TG_API_HASH=abcdef1234567890abcdef1234567890 \
            -e BASE_URL=https://example.com \
            -p 3042:3042 \
            srivmanish/telegram-to-rss1:dev

      - name: Wait for container to be ready
        run: sleep 10

      - name: Check if service is responding
        run: |
          curl -f http://localhost:3042 || (echo "Service failed to respond" && exit 1)

      - name: Cleanup container
        if: always()
        run: docker rm -f telegram_test
