name: Build Docker images tag
on:
  push:
    # Run pipeline for release tags
    #tags:
     # - "v*.*.*"
     branches:
      - Snekha/test

jobs:
  build-tag:
    runs-on: [ubuntu-22.04]
    # Only run on pushed tags (and explicitely ignore scheduled runs)
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') && github.event_name != 'schedule'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: srivmanish
          password: Hcl@20252026
      - name: Build tag and latest
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: srivmanish/telegram-to-rss1:dev
          platforms: linux/amd64,linux/arm64
