name: Build Docker image dev
on:
  push:
    # Run pipeline for commits on branch main
    branches:
      - "main"
      - "Snekha/test" #edited
      - "!testing/**"
      - "!feature/**"
      - "!hotfix/**"

jobs:
  build-dev:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: srivmanish
          password: Hcl@20252026
      - name: Build and push dev
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: srivmanish/telegram-to-rss1:dev
          platforms: linux/amd64,linux/arm64
      - name: Run container (optional)
        run: |
          docker run --rm -d \
            -e DATA_DIR=/data \
            -e BIND=0.0.0.0:3042 \
            -p 3042:3042 \
            srivmanish/telegram-to-rss1:dev
